export const PermissionPermission = {
  GET_PERMISSION: 'PERMISSION.GET',
  GET_PERMISSIONS: 'PERMISSION.LIST',
  CREATE_PERMISSION: 'PERMISSION.CREATE',
  UPDATE_PERMISSION: 'PERMISSION.UPDATE',
  DELETE_PERMISSION: 'PERMISSION.DELETE',
} as const;
