/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  appliedStepsCount: Generated<number>;
  checksum: string;
  finishedAt: Timestamp | null;
  id: string;
  logs: string | null;
  migrationName: string;
  rolledBackAt: Timestamp | null;
  startedAt: Generated<Timestamp>;
}

export interface AuthServicePermissions {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface AuthServicePlatforms {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface AuthServiceRefreshTokens {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  platformId: number;
  updatedAt: Generated<Timestamp>;
  userId: number;
  value: string;
}

export interface AuthServiceRolePermissions {
  permissionId: number;
  roleId: number;
}

export interface AuthServiceRoles {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
  platformId: number;
  updatedAt: Generated<Timestamp>;
}

export interface AuthServiceUserRoles {
  roleId: number;
  userId: number;
}

export interface AuthServiceUsers {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  isActive: Generated<boolean>;
  passwordHash: string;
  platformId: number;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  _PrismaMigrations: _PrismaMigrations;
  authServicePermissions: AuthServicePermissions;
  authServicePlatforms: AuthServicePlatforms;
  authServiceRefreshTokens: AuthServiceRefreshTokens;
  authServiceRolePermissions: AuthServiceRolePermissions;
  authServiceRoles: AuthServiceRoles;
  authServiceUserRoles: AuthServiceUserRoles;
  authServiceUsers: AuthServiceUsers;
}
