/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  appliedStepsCount: Generated<number>;
  checksum: string;
  finishedAt: Timestamp | null;
  id: string;
  logs: string | null;
  migrationName: string;
  rolledBackAt: Timestamp | null;
  startedAt: Generated<Timestamp>;
}

export interface AuthServicePermissions {
  code: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface AuthServicePlatforms {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface AuthServiceRefreshTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  isActive: Generated<boolean>;
  platformId: number;
  updatedAt: Generated<Timestamp>;
  userId: number;
  value: string;
}

export interface AuthServiceRoles {
  code: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
  platformId: number;
  updatedAt: Generated<Timestamp>;
}

export interface AuthServiceRolesPermissions {
  permissionId: number;
  roleId: number;
}

export interface AuthServiceUsers {
  avatar: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  id: Generated<number>;
  isActive: Generated<boolean>;
  lastLoginAt: Timestamp | null;
  password: string;
  phone: string | null;
  platformId: number;
  updatedAt: Generated<Timestamp>;
}

export interface AuthServiceUsersRoles {
  roleId: number;
  userId: number;
}

export interface DB {
  _PrismaMigrations: _PrismaMigrations;
  authServicePermissions: AuthServicePermissions;
  authServicePlatforms: AuthServicePlatforms;
  authServiceRefreshTokens: AuthServiceRefreshTokens;
  authServiceRoles: AuthServiceRoles;
  authServiceRolesPermissions: AuthServiceRolesPermissions;
  authServiceUsers: AuthServiceUsers;
  authServiceUsersRoles: AuthServiceUsersRoles;
}
